const pagesData = [
  {
    _id: '6374956747bbe1f1e03519ff',
    active: true,
    domain: 'pks2974.medium.com',
    url: 'https://pks2974.medium.com/iframe-간단-정리하기-1cd866b71c8f',
    title:
      'iframe 간단 정리하기. iframe 을 사용해볼 일이 생겨, 이참에 잘 모르고 있던… | by 박성룡 ( Andrew park ) | Medium',
    keywords: ['keyword1'],
    refs: [],
    backRefs: [],
    comments: [],
    __v: 0,
  },
  {
    _id: '6374956747bbe1f1e0351a00',
    active: true,
    domain: 'developer.mozilla.org',
    url: 'https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/search',
    title: 'String.prototype.search() - JavaScript | MDN',
    keywords: ['keyword2'],
    refs: [],
    backRefs: [],
    comments: [],
    __v: 0,
  },
  {
    _id: '6374956747bbe1f1e0351a01',
    active: true,
    domain: 'stackoverflow.com',
    url: 'https://stackoverflow.com/questions/50698083/find-tag-name-of-svg-element-using-d3',
    title:
      'javascript - Find tag name of svg element using D3 - Stack Overflow',
    keywords: ['keyword3'],
    refs: [],
    backRefs: [],
    comments: [],
    __v: 0,
  },
  {
    _id: '6374956747bbe1f1e0351a02',
    active: true,
    domain: 'using-d3js.com',
    url: 'http://using-d3js.com/05_08_links.html',
    title: 'Links',
    keywords: ['keyword4'],
    refs: [],
    backRefs: [],
    comments: [],
    __v: 0,
  },
  {
    _id: '6374956747bbe1f1e0351a03',
    active: true,
    domain: 'www.google.com',
    url: 'https://www.google.com/search?client=safari&rls=en&q=d3+link+generator&ie=UTF-8&oe=UTF-8',
    title: 'd3 link generator - Google 검색',
    keywords: ['keyword5'],
    refs: [],
    backRefs: [],
    comments: [],
    __v: 0,
  },
  {
    _id: '6374956747bbe1f1e0351a04',
    active: true,
    domain: 'using-d3js.com',
    url: 'http://using-d3js.com/02_04_reordering_elements.html',
    title: 'Reordering Elements',
    keywords: ['keyword6'],
    refs: [],
    backRefs: [],
    comments: [],
    __v: 0,
  },
  {
    _id: '6374956747bbe1f1e0351a05',
    active: true,
    domain: 'nextjs.org',
    url: 'https://nextjs.org/docs/routing/dynamic-routes',
    title: 'Routing: Dynamic Routes | Next.js',
    keywords: ['keyword7'],
    refs: [],
    backRefs: [],
    comments: [],
    __v: 0,
  },
  {
    _id: '6374956747bbe1f1e0351a06',
    active: true,
    domain: 'stackoverflow.com',
    url: 'https://stackoverflow.com/questions/72039417/uncaught-in-promise-nested-async-function-promise-error-handling',
    title:
      'javascript - uncaught in promise nested async function promise error handling - Stack Overflow',
    keywords: ['keyword8'],
    refs: [],
    backRefs: [],
    comments: [],
    __v: 0,
  },
  {
    _id: '6374956747bbe1f1e0351a07',
    active: true,
    domain: 'cloud.mongodb.com',
    url: 'https://cloud.mongodb.com/v2/6322b2a7006da244f5df3260#metrics/replicaSet/6322b359d4a2683b145e1b11/explorer/beadit-test/beadworks/find',
    title: 'Data | Cloud: MongoDB Cloud',
    keywords: ['keyword9'],
    refs: [],
    backRefs: [],
    comments: [],
    __v: 0,
  },
  {
    _id: '6374956747bbe1f1e0351a08',
    active: true,
    domain: 'github.com',
    url: 'https://github.com/d3/d3-selection/blob/v3.0.0/README.md#selection_datum',
    title: 'd3-selection/README.md at v3.0.0 · d3/d3-selection',
    keywords: ['keyword10'],
    refs: [],
    backRefs: [],
    comments: [],
    __v: 0,
  },
];

module.exports = pagesData;
